### ISSUE TITLE
Closing Visual Studio Code does not remove the RPC information

### ISSUE THREAD

**Issue by justalemon** [maxerbox/vscode-discord#7]
Even if you close VS Code, you still will see information about the file and folder open.
![Information about Visual Studio Code is still on Discord](https://user-images.githubusercontent.com/11861253/33113322-9c43e23a-cf36-11e7-8725-f33581a06ae4.png)

**Comment by fratik** [comment]
it's an issue directly with Discord. just reload it. (Ctrl+R)

**Comment by maxerbox** [comment]
It's because the activity is not reset when VScode is closing, I'm looking for an event to handle it.

**Comment by maxerbox** [comment]
With the disposable client, the Rich Presence is reset when Visual Studio Code is closed, but it's still displaying "Playing Visual Studio Code".
To fix it, you need to add Visual Studio Code as a game.

**Comment by justalemon** [comment]
Discord says that is recomendable to send a shudown signal when the app closes, so the RPC server removes the status.

**Comment by maxerbox** [comment]
@justalemon May you have some docs about sending a shutdown signal to discord, it could be helpfull

**Comment by justalemon** [comment]
@maxerbox https://discordapp.com/developers/docs/rich-presence/how-to
![image](https://user-images.githubusercontent.com/11861253/33334484-c2543b7a-d448-11e7-9d50-1c39f9a73706.png)

**Comment by maxerbox** [comment]
Yeah, it is calling the  `static void Destroy(BaseConnection*&);` function,

https://github.com/discordapp/discord-rpc/blob/master/src/discord-rpc.cpp#L312

https://github.com/discordapp/discord-rpc/blob/master/src/connection_win.cpp#L66

It cannot be done with the discord-rpc server.

**Comment by maxerbox** [comment]
I hope it is fixed now ^^

**Comment by Alexejhero** [comment]
Hate to dig up such an old issue, but the problem is still there.
